# Generated by Django 4.0.4 on 2022-04-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year_of_publication',
            field=models.IntegerField(default=2000),
        ),
    ]
