# Generated by Django 4.0.4 on 2022-04-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_year_of_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_of_publication',
            field=models.IntegerField(null=True),
        ),
    ]
