# Generated by Django 4.0.4 on 2022-04-23 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_book_creator_alter_book_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='creator',
        ),
    ]
