# Generated by Django 4.0.4 on 2022-04-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_created_at_location_updated_at'),
        ('books', '0017_book_created_at_book_updated_at_alter_book_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Not classified', "This book can't be classified as a particular genre"), ('Action', 'Action and adventure books constantly have you on the edge of your seat with excitement'), ('Classics', 'You may think of these books as the throwback readings you were assigned in English class. '), ('Comic', "The stories in comic books and graphic novels are presented to the reader through engaging, sequential narrative art (illustrations and typography) that's either presented in a specific design or the traditional panel layout you find in comics."), ('Detective', 'The plot always revolves around a crime of sorts that must be solved—or foiled—by the protagonists.')], default='Action', max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='books', to='locations.location'),
        ),
    ]
