# Generated by Django 4.0.4 on 2022-04-30 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_book_genre_alter_book_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.TextField(choices=[('en', 'English'), ('de', 'German'), ('cn', 'Chinese')], default='en'),
        ),
    ]
