# Generated by Django 4.0.4 on 2022-04-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.TextField(choices=[('en', 'English'), ('de', 'German'), ('cn', 'Chinese'), ('es', 'Spanish')], default='en'),
        ),
    ]
