# Generated by Django 4.0.4 on 2022-04-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_alter_book_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='locations',
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('cn', 'Chinese'), ('es', 'Spanish')], default='en', max_length=2),
        ),
    ]
