# Generated by Django 4.0.4 on 2022-05-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_remove_location_books'),
        ('books', '0021_remove_book_locations_alter_book_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='books', to='locations.location'),
        ),
    ]
