# Generated by Django 4.0.4 on 2022-04-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_remove_book_locations_alter_book_language'),
        ('locations', '0002_location_created_at_location_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='locations_of_books', to='books.book'),
        ),
    ]
